services:
  backend:
    build: [NeoFlixBackend_path]
    container_name: backend
    volumes:
      - backend_db:[NeoFlixBackend_db_path]
    env_file:
      - [.env_path]
    ports:
      - 8000:8000
    networks:
      - shared_network
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [sonarr_path]:/config
      - [tv_path]:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - shared_network
  radarr:
      image: lscr.io/linuxserver/radarr:latest
      container_name: radarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
      volumes:
        - [radarr_path]:/config
        - [movies_folder]:/movies
      ports:
        - 7878:7878
      restart: unless-stopped
      networks:
        - shared_network
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [prowlarr_path]:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - shared_network
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - [qbittorrent_path]:/config
      - [downloads_path]:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - shared_network
networks:
  shared_network:
    driver: bridge
volumes:
  backend_db:

